name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/docs.yml'
  release:
    types: [ published ]

env:
  GO_VERSION: '1.23'
  CGO_ENABLED: 1

jobs:
  # Check if changes are docs-only
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      docs-only: ${{ steps.filter.outputs.docs }}
      go-changes: ${{ steps.filter.outputs.go }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            docs:
              - 'docs/**'
              - 'README.md'
              - '.github/workflows/docs.yml'
            go:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - '**/*.yml'
              - '**/*.yaml'
              - '**/*.json'
              - '**/*.md'
              - '**/*.txt'
              - '**/*.sh'
              - '**/*.dockerfile'
              - '**/Dockerfile*'

  # Lint and format check (skip for docs-only)
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.go-changes == 'true' }}
    needs: changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=5m

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Check formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Code is not formatted. Please run 'gofmt -s -w .'"
            gofmt -s -l .
            exit 1
          fi

  # Unit tests (skip for docs-only)
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.go-changes == 'true' }}
    needs: changes
    strategy:
      matrix:
        go-version: [1.21, 1.22, 1.23]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella

  # Integration tests (skip for docs-only)
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.go-changes == 'true' }}
    needs: [changes, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run integration tests
        run: go test -v -tags=integration ./integration_test.go

  # Security scanning (skip for docs-only)
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.go-changes == 'true' }}
    needs: changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run gosec security scanner
        uses: securecodewarrior/github-action-gosec@master
        with:
          args: '-fmt sarif -out results.sarif ./...'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: results.sarif

  # Documentation generation (run for all changes)
  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    needs: [changes, test]
    if: always() && needs.test.result != 'failure'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger docs
        run: |
          if [ -f "cmd/goauth/main.go" ]; then
            swag init -g cmd/goauth/main.go -o docs
          else
            echo "No main.go found for Swagger generation"
          fi

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: swagger-docs
          path: docs/

  # Library validation (skip for docs-only)
  validate:
    name: Library Validation
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.go-changes == 'true' }}
    needs: [changes, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Validate library structure
        run: |
          if [ ! -f "goauth.go" ]; then
            echo "Error: goauth.go not found"
            exit 1
          fi
          echo "Library structure is valid"

      - name: Check module compatibility
        run: go mod verify

      - name: Test library imports
        run: |
          # Test that the library can be imported
          go list -f '{{.ImportPath}}' ./...

  # Release automation (skip for docs-only)
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [changes, lint, test, integration, security, validate, docs]
    if: github.event_name == 'release' && github.event.action == 'published' && needs.changes.outputs.go-changes == 'true'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: swagger-docs
          path: docs/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            docs/**/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Dependency vulnerability check (skip for docs-only)
  vulncheck:
    name: Vulnerability Check
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.go-changes == 'true' }}
    needs: changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run govulncheck
        run: govulncheck ./...

  # Performance benchmarks (skip for docs-only)
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.go-changes == 'true' }}
    needs: [changes, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run benchmarks
        run: go test -bench=. -benchmem ./...

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmark.out 